name: audioplayers_elinux
description: Flutter plugin for playing audio with other Flutter widgets on Embedded Linux.
homepage: https://github.com/sony/flutter-elinux-plugins/
repository: https://github.com/sony/flutter-elinux-plugins/tree/main/packages/auidoplayers
version: 0.1.0

flutter:
  plugin:
    platforms:
      elinux:
        pluginClass: AudioplayersElinuxPlugin

dependencies:
  audioplayers_platform_interface: ^7.0.0
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"
